DROP TABLE IF EXISTS Students, Faculty, Admins, Courses, Classes;

CREATE TABLE Students
(
  BannerID INT NOT NULL AUTOINCREMENT,
  Password TEXT NOT NULL,
  Name TEXT NOT NULL,
  Address TEXT NOT NULL,
  Phone_Number NUMERIC(10) NOT NULL,
  Email TEXT NOT NULL,
  PRIMARY KEY (BannerID)
);

CREATE TABLE Faculty
(
  BannerID INT NOT NULL AUTOINCREMENT,
  Password TEXT NOT NULL,
  Name TEXT NOT NULL,
  Address TEXT NOT NULL,
  Phone_Number NUMERIC(10) NOT NULL,
  Email TEXT NOT NULL,
  PRIMARY KEY (BannerID)
);

CREATE TABLE Admins
(
  ID INT NOT NULL AUTOINCREMENT,
  Password TEXT NOT NULL,
  Name TEXT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE Courses
(
  CourseID INT NOT NULL AUTOINCREMENT,
  Title TEXT NOT NULL,
  Major TEXT NOT NULL,
  Semester TEXT NOT NULL,
  Prerequisites TEXT NOT NULL,
  PRIMARY KEY (CourseID)
);

CREATE TABLE Classes
(
  ClassID INT NOT NULL AUTOINCREMENT,
  SeatsAvailable INT NOT NULL,
  CourseID INT NOT NULL,
  PRIMARY KEY (ClassID),
  FOREIGN KEY (CourseID) REFERENCES Courses(CourseID)
);

